

use std::str::FromStr;
use crate::ast::{Expr, Opr};

grammar;

//이거 좌측이 문법 구조->러스트(AST) 구조 이런느낌이네, :으로 좌/우 구분하는거고
    //보고 읽을 수 있는 수준으로만 이해하라

pub Expr: Box<Expr> = { //Expr이라는건 코드에서 Box<Expr>로 변환된다.
    <n:Num> => Box::new(Expr::Num(n)),  //n:Num은 코드에서 이렇게 변환된다.
    "(" <l:Expr> <op:ExprOp> <r:Expr> ")" => Box::new(Expr::Op(l, op, r)),
    "(" <e:Expr> ")" => e,
};

ExprOp: Opr = {
    "+" => Opr::Add,
    "-" => Opr::Sub,
};

Num: i32 = {
    r"(-)?[0-9]+" => i32::from_str(<>).unwrap(),
}